version: '3.1'

services: 
    db:
        image: postgres
        restart: always
        ports:
          - "5433:5432"
        volumes:
          - ./pgdb/:/var/lib/postgresql/data
        environment: 
          POSTGRES_PASSWORD: 12345
          POSTGRES_USER: user
          POSTGRES_DB: auth

    adminer:
      image: adminer
      restart: always
      ports:
          - 8081:8080

