"""empty message

Revision ID: c2057bf343fa
Revises: ba263ae08178
Create Date: 2022-06-09 20:45:54.879930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2057bf343fa'
down_revision = 'ba263ae08178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('story', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('story', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('story_author_id_fkey', 'story', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('story_author_id_fkey', 'story', 'user', ['author_id'], ['id'])
    op.alter_column('story', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('story', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
