version: '3.1'

services: 
    web:
        build: .
        #        dockerfile: Dockerfile
        #        context: .
        command:  flask run -h 0.0.0.0 -p 5000
        ports: 
            - 5002:5000
        depends_on: 
            - "redisdb"

    redisdb:
        image: redis
        ports: 
            - 6380:6379
        volumes: 
            - ./rdb:/data

    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
    
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
    
        
        
