# Generated by Django 4.0.2 on 2022-03-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('1', 'Sayt islemir'), ('2', 'Menimle elaqe saxlayin')], max_length=50, verbose_name='Movzu'),
        ),
    ]
