# Generated by Django 4.0.2 on 2022-03-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_contact_created_at_contact_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='media/categories/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
