# Generated by Django 4.0.2 on 2022-03-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_tag_alter_category_options_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
